#!/bin/bash

MESOS_VERSION=0.27.0
BUILD_URL=http://pokgsa.ibm.com/projects/i/ibm-mesos/dailybuild-deb/last/
TOP_DIR=`pwd`

if [ ! -d $TOP_DIR/files ];then
	mkdir -p $TOP_DIR/files
fi

wget $BUILD_URL -O index.html

BUILD_PACKAGE=`cat index.html|grep mesos_${MESOS_VERSION}|   awk '{print $5}' | cut -c7- | cut -f1 -d '"'`
rm -rf index.html
wget $BUILD_URL/$BUILD_PACKAGE; mv $BUILD_PACKAGE $TOP_DIR/files/

docker build -t hchenxa1986/mesos-slave:${MESOS_VERSION} --no-cache ${TOP_DIR}
